-- 007_post_visibility.sql — 허용된 계정만 볼 수 있는 글을 만든다.
--
-- # 왜 status로 안 되나
--
-- `posts.status`에는 CHECK이 걸려 있고 SQLite는 CHECK을 ALTER로 못 고친다.
-- 값을 늘리려면 테이블을 새로 만들어 옮겨야 하는데, 그건 "컬럼이나 테이블을
-- 삭제하는 마이그레이션은 만들지 않는다"와 정면으로 부딪힌다.
--
-- 뜻도 다르다. status는 **글이 어디까지 왔나**를 말한다(안 쓴 자리 / 아카이브
-- 본문 / 골라 세운 글). 여기서 필요한 것은 **누가 볼 수 있나**라 축이 다르고,
-- 축이 다른 것을 한 칸에 밀어 넣으면 "draft이면서 비공개"를 적을 수 없다.
--
-- # CHECK을 걸지 않는다
--
-- 값이 늘어날 수 있는 칸이다(지금은 public·private 둘이지만 나중에 사람별
-- 허용 목록이 생기면 하나 더 붙는다). 검증은 애플리케이션이 한다 —
-- `posts.source`와 같은 판단이다.
--
-- # 기본값은 'public'이다
--
-- 기존 1,261편은 전부 지금처럼 보여야 한다. 새 값은 사람이 admin에서 켠다.
ALTER TABLE posts ADD COLUMN visibility TEXT NOT NULL DEFAULT 'public';
